### ISSUE TITLE
owner fail

### ISSUE THREAD

**Issue by matyasrr** [vmanzoni/discord-priority-speaker-bot#1]
It's impossible to set owner or administator.

**Comment by vmanzoni** [comment]
Greetings,

Can you be more specific about the problem you're encountering?

**Comment by matyasrr** [comment]
Hi, when i set up in botSettings.json owner or administatorrole, i got message in log, that i don't have permissions to start command. I tried nick, nick with # and number and my email. What is needed to fill?
